# Workflow to use continuos delivery

name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test_and_build:
    name: Test and build the distributable generator-esmodules-generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: run quality check
        run: npm run quality-check

      - name: build the dist folder
        run: npm run build

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: distributable-generator-esmodules-generator
          path: |
            dist
            LICENSE
            README.md
            package.json
          retention-days: 1

  release:
    name: Create the release of the generator-esmodules-generator into GitHub
    runs-on: ubuntu-latest
    needs: test_and_build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: create a new tag
        id: tag
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          tag_prefix: 'v'

      - name: create a new release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.tag.outputs.tagname != '' && steps.tag.outputs.tagname || format('v{0}', steps.tag.outputs.version) }}
        with:
          tag_name: $TAG
          release_name: Release $TAG
          body_path: RELEASE_NOTES.md
