# Workflow to use continuos delivery

name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    name: Test and build the distributable generator-esmodules-generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: run quality check
        run: npm run quality-check

      - name: build the dist folder
        run: npm run build

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: distributable-generator-esmodules-generator
          path: |
            dist
            LICENSE
            README.md
            package.json
          retention-days: 1

  release:
    name: Create the release of the generator-esmodules-generator into GitHub
    runs-on: ubuntu-latest
    needs: test_and_build
    steps:
      - name: download the distributable generator-esmodules-generator generator
        uses: actions/download-artifact@v4
        with:
          name: distributable-generator-esmodules-generator

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: link the generator-esmodules-generator generator
        run: npm link

      - name: obtain the version of generator-esmodules-generator
        run: echo "GENERATOR_ESMODULES_GENERATOR_VERSION=$(npm view generator-esmodules-generator version)" >> "$GITHUB_OUTPUT"

      - name: create and push a new tag
        run: |
          git tag $GENERATOR_ESMODULES_GENERATOR_VERSION
          git push origin $GENERATOR_ESMODULES_GENERATOR_VERSION
