# Workflow based in lint, format and tests of the source code

name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    name: Test source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: install dependencies
        run: npm ci

      - name: run linter
        run: npm run lint

      - name: run formatter
        run: npm run format

      - name: run tests
        run: npm run test

  create_generator:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['>=18.17.0', '20.x']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: print node-version
        run: echo ${{ matrix.node-version }}

      - name: install yeoman
        run: npm install -g yo

      - name: install dependencies
        run: npm ci

      - name: link the generator
        run: npm link

      - name: create a new folder
        working-directory: ../
        run: mkdir -p test-generator

      - name: create a new generator
        working-directory: ../test-generator
        run: yo esmodules-generator

      - name: run linter
        working-directory: ../test-generator
        run: npm run lint

      - name: run formatter
        working-directory: ../test-generator
        run: npm run format

      - name: run tests
        working-directory: ../test-generator
        run: npm run test
